### ISSUE TITLE
Enable xrender-sync-fence

### ISSUE THREAD

**Issue by RafalSkolasinski** [regolith-linux/regolith-compositor-picom-glx#2]
I was struggling with some very weird refresh problems with NVidia proprietary drivers: terminal (both tilix and alacritty) was failing to render proper output e.g. during cycling through history of commands and moving cursor left and right.

It seems that setting 
```bash
xrender-sync-fence = true
```
in picom config file fixed the issue. 

This patch https://github.com/regolith-linux/regolith-compositor-compton-glx/commit/d9a4da6f84955ea2cc38354e964d9fd08fa92047#diff-2245023265ae4cf87d02c8b6ba991139R45
applies same option to compton config (that was my inspiration to try it).

**Comment by kgilmer** [comment]
Hi @RafalSkolasinski are you opening this issue to simply help others that may have the issue or are you suggesting adding this flag as default for all users?

**Comment by RafalSkolasinski** [comment]
Hey @kgilmer. I think it would make sense to put it as default. If you don't think it's good idea then for sure make a note on compositor's page in docs. 

This was a significant blocker for me to get Regolith works on all of my machines: having a wrong information at random displayed in terminal was just a no-go. I think only on 3rd approach I managed when I found this option.

**Comment by kgilmer** [comment]
Ok I'll review the picom source regarding `xrender-sync-fence` and do some local testing.

**Comment by moritzheiber** [comment]
This has shipped with the 1.5.1 release.
