### ISSUE TITLE
init passed -f to picom thereby enforcing fading

### ISSUE THREAD

**Issue by christo-auer** [regolith-linux/regolith-compositor-picom-glx#3]
`init` passes `-f` to picom thereby enforcing fading regardless of a provided user config which may disable fading.

Proposed solution: remove `-f` flag and setup fading in config file.

**Comment by moritzheiber** [comment]
@kgilmer You're the original author, what’s your take on this?

**Comment by kgilmer** [comment]
Verified issue.  Yeah the shipped picom already enables fading so the command line arg is redundant as well as limiting user options for configuration.

Verified removing flag from "init" script does not produce any obvious regressions.

**Comment by kgilmer** [comment]
Thanks for the bug report @christo-auer .  This fix is building into the `unstable` PPA currently and should be availble in the `stable` PPA in a week or so.  And will migrate to `release` in Regolith 2.0.

**Comment by christo-auer** [comment]
Awesome, thanks! Looking forward to trying out Regolith 2.0!

**Comment by kgilmer** [comment]
Actually we had another bug fix release so this has been added to Regolith 1.5.2.
