### ISSUE TITLE
Ilia is always inactive window

### ISSUE THREAD

**Issue by jrieko** [regolith-linux/regolith-compositor-picom-glx#8]
When opening menus in Ilia, the window is always deemed inactive by picom. After setting dim/opacity/etc for inactive windows, ilia menus are dimmed/etc.

I'm locally setting `"name *= 'ilia'"` to [always focused by picom](https://github.com/regolith-linux/regolith-compositor-picom-glx/blob/master/config#L180), seems to have the desired effect so far. Let me know if there's a more appropriate mechanism to solve this, otherwise I can PR this solution.

**Comment by jrieko** [comment]
Sorry, scratch that. It was caused by broken config locally.

Just to check I'm not missing something, it's not presently possible to have partial configs in `~/.config/regolith/...`, which override and merge with those in `/etc/regolith/`, correct? I'd guess because that would require regolith to do such merging external to the program being configured.

**Comment by kgilmer** [comment]
> Sorry, scratch that. It was caused by broken config locally.
> 
> Just to check I'm not missing something, it's not presently possible to have partial configs in `~/.config/regolith/...`, which override and merge with those in `/etc/regolith/`, correct? I'd guess because that would require regolith to do such merging external to the program being configured.

Hi @jrieko , what version of Regolith are you using?  The current release is 2.2, and 3.0 is in beta.  The former should use user config directory base of `~/.config/regolith2` and that will change in the obvious way for the 3.0 release.  Regolith 1.x did not support i3 config partials.  Regolith 2.x onward does.  You can look at the bottom of `/etc/regolith/i3/config` to see where partials may be loaded from.  HTH
